spring:
  application:
    name: lecture-service
#  r2dbc:
#    url: r2dbc:h2:mem:///msa
#    username: sa
#    password:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: lecture
    producer:
      bootstrap-servers: localhost:9092


logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
#debug: true

